name: CI

on: [push]

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run fmt:check
      - run: npm run lint

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm test

  inProgress:
    name: In-progress acceptance tests
    runs-on: ubuntu-latest
    needs: [analysis, unit]
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          config: integrationFolder=cypress/tests/inProgress

  regression:
    name: Regression tests
    runs-on: ubuntu-latest
    needs: [analysis, unit]
    env:
      CI: true

    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          config: integrationFolder=cypress/tests/regression
